---
title: 'Biostat 778: Homework 1'
output:
  pdf_document: default
  html_document: default
---

## 1. Convergence of Newton's Method

Consider Newton's method. Given $f\in C^2$, let $x_\infty$ be such that $f(x_\infty) = 0$ and $f^\prime(x_\infty) \ne 0$. Use the Shrinking Lemma (a.k.a. Contraction Mapping Theorem) to prove that there exists a $\delta$ such that for all $x\in[x_\infty-\delta, x_\infty+\delta]$, the sequence generated by Newton's method,

\[
x_n = x_{n-1} + \frac{f(x_{n-1})}{f^\prime(x_{n-1})}
\]
converges to $x_\infty$ as $n\rightarrow\infty$.




## 3. Improving consistent estimators

Let $\tilde{\theta}_n$ be an estimator of $\theta$ such that $\sqrt{n}(\tilde{\theta}_n-\theta)\rightarrow\mathcal{N}(0, \Sigma(\theta))$ and $\Sigma(\theta)<\infty$. Let $\hat{\theta}_n$ be the maximum likelihood estimator of $\theta$. Let $\tilde{\theta}^{(1)}_n$ be single iteration of Newton's method applied to $\tilde{\theta}$, i.e.
\[
\tilde{\theta}^{(1)}_n = \tilde{\theta}_n -\ell^{\prime\prime}(\tilde{\theta}_n)^{-1}\ell^\prime(\tilde{\theta}_n)
\]
Show that $\tilde{\theta}^{(1)}_n$ is asymptotically equivalent to the MLE.